CREATE TABLE NAMES(
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20) ,
FULL_NAME  AS FIRST_NAME +' '+LAST_NAME   PERSISTED 
)

SELECT * FROM NAMES

DROP TABLE NAMES 

INSERT INTO NAMES VALUES ('RAJAT' , 'DUTTA','RAJATBALUNI')


